/**
 * Writing a plugin for orknux-server.
 *
 * Everything exported here is safe to import from a plugin: the three classes
 * and the `orknux` helpers are bindings to what the sandbox already defines, and
 * the rest is types, constants and pure functions. Nothing reaches for a file, a
 * network or a Node built-in, because a plugin that imported one would bundle it
 * and the sandbox would refuse the result.
 *
 * The tooling — bundling a plugin, and loading a built one to check it — is
 * `@orknux/plugin/tooling`, and is deliberately not here.
 */
export {
  orknux,
  OrknuxFunction,
  OrknuxFunctionTool,
  OrknuxObject,
  OrknuxParameter,
  OrknuxPlugin,
  OrknuxSkill,
  OrknuxTool,
  OrknuxType,
} from './contract.js';
export type {
  OrknuxFunctionConstructor,
  OrknuxFunctionToolConstructor,
  OrknuxObjectConstructor,
  OrknuxParameterConstructor,
  OrknuxPluginBase,
  OrknuxSkillConstructor,
  OrknuxToolConstructor,
  OrknuxTypeConstructor,
} from './contract.js';

export { definePlugin, fn, functionTool, param, tool } from './define.js';
export type { OrknuxPluginSpec } from './define.js';

export {
  ACTION_VALUE_TYPES,
  ARGUMENT_TYPES,
  API_VERSION,
  CAPABILITIES,
  CONNECTION,
  CONNECTION_TYPES,
  IDENTIFIER,
  LIBRARY_PATH,
  MAX_ACTIONS,
  MAX_ACTION_PARAMETERS,
  MAX_CONNECTION_TYPES,
  MAX_FUNCTIONS,
  MAX_LIBRARIES,
  MAX_LIBRARY_PATH_LENGTH,
  MAX_OBJECTS,
  MAX_OPTIONS,
  MAX_PARAMETERS,
  MAX_PERMISSIONS,
  MAX_PROPERTIES,
  MAX_SKILLS,
  MAX_SKILL_CHARS,
  MAX_SKILL_NAME_LENGTH,
  MAX_SOURCE_BYTES,
  MAX_TOOLS,
  MAX_TYPES,
  MAX_TYPE_PARAMETERS,
  OBJECT_NAME,
  PARAMETER_TYPES,
  PERMISSIONS,
  PLUGIN_ID,
  PROPERTY_KINDS,
  SUPPORTED_API_VERSIONS,
  TYPE_BASES,
  VALUE_TYPES,
} from './limits.js';

export type {
  OrknuxActionContext,
  OrknuxActionDeclaration,
  OrknuxActionOutput,
  OrknuxActionParameter,
  OrknuxActionValueType,
  OrknuxArgs,
  OrknuxArgumentType,
  OrknuxArgumentValues,
  OrknuxBinaryResponse,
  OrknuxConnectionAuthType,
  OrknuxConnectionTypeDeclaration,
  OrknuxCapability,
  OrknuxConnectionHandle,
  OrknuxConnectionType,
  OrknuxFunctionDeclaration,
  OrknuxFunctionInstance,
  OrknuxFunctionToolDeclaration,
  OrknuxFunctionToolInstance,
  OrknuxHelpers,
  OrknuxObjectDeclaration,
  OrknuxObjectInstance,
  OrknuxParam,
  OrknuxParameterDeclaration,
  OrknuxParameterInstance,
  OrknuxParameterType,
  OrknuxPermission,
  OrknuxPluginConstructor,
  OrknuxPluginInstance,
  OrknuxPropertyKind,
  OrknuxProperty,
  OrknuxResponse,
  OrknuxRunContext,
  OrknuxSettings,
  OrknuxSkillDeclaration,
  OrknuxSkillInstance,
  OrknuxStorePut,
  OrknuxToolDeclaration,
  OrknuxToolInstance,
  OrknuxTypeBase,
  OrknuxTypeDeclaration,
  OrknuxTypeInstance,
  OrknuxTypeSuggestion,
  OrknuxTypeVerdict,
  OrknuxValues,
  OrknuxValueType,
  SlackConnectionArgument,
  SlackLinkedMessage,
  SlackMention,
  SlackPost,
  SlackReaction,
  SlackSearchResult,
  SlackSuggestions,
  SlackThread,
  SlackThreadMessage,
  SlackUserInfo,
} from './types.js';

export {
  qualifiedName,
  validate,
  validateActions,
  validateApiVersion,
  validateCapabilities,
  validateConnectionTypes,
  validateFunctions,
  validateId,
  validateLibraries,
  validateObjects,
  validateParameters,
  validatePermissions,
  validateSkills,
  validateTools,
  validateTypes,
} from './validate.js';
export type {
  DeclaredAction,
  DeclaredActionParam,
  DeclaredConnectionType,
  DeclaredFunction,
  DeclaredObject,
  DeclaredParam,
  DeclaredParameter,
  DeclaredProperty,
  DeclaredSkill,
  DeclaredTool,
  DeclaredType,
  Declaration,
  Problem,
} from './validate.js';
